routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Auth::routes();

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::group(['prefix' => 'home'], function () {
    Route::get('/', 'HomeController@index');
});

require __DIR__ . '/web/users.php';

require __DIR__ . '/web/business.php';

require __DIR__ . '/web/dashboard.php';

require __DIR__ . '/web/products.php';

require __DIR__ . '/web/wish_lists.php';

require __DIR__ . '/web/orders.php';

require __DIR__ . '/web/about.php';

require __DIR__ . '/web/utilities.php';

require __DIR__ . '/web/globals.php';

require __DIR__ . '/web/user_service.php';

app/Product.php
<?php

namespace app;

use App\Category;
use App\Eloquent\Model;

class Product extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'products';
    protected $appends = ['num_of_reviews'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_id',
        'user_id',
        'name',
        'description',
        'price',
        // 'stock',
        'features',
        // 'barcode',
        // 'condition',
        'rate_val',
        'rate_count',
        // 'low_stock',
        'status',
        'parent_id',
    ];
    protected $hidden = ['details', 'created_at'];
    public function details()
    {
        return $this->hasMany('App\OrderDetail');
    }
    public function categories()
    {
        return $this->belongsTo('App\Category', 'category_id');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function group()
    {
        return $this->hasMany('App\Product', 'products_group', 'products_group');
    }
    public static function create(array $attr = [])
    {
        if (isset($attr['features']) && is_array($attr['features'])) {
            $attr['features'] = json_encode($attr['features']);
        }
        return parent::create($attr);
    }
    public function getLastCommentsAttribute()
    {
        return $this->details->take(5);
    }
    public function getFirstImageAttribute()
    {
        $features_array = $this->features;
        return $features_array['images'][0];
    }
    public function getFeaturesAttribute()
    {
        return json_decode($this->attributes['features'], true);
    }
    public function scopeActives($query)
    {
        return $query->where('status', 1);
                     // ->where('stock', '>', 0);
    }
    public function scopeInactives($query)
    {
        return $query->where('status', 0);
    }
    public function scopeSearch($query, $seed)
    {
        return $query->where('name', 'like', '%'.$seed.'%')
            ->orWhere('description', 'like', '%'.$seed.'%')
            ->orWhere('features', 'like', '%'.$seed.'%')
            ->orWhere('brand', 'like', '%'.$seed.'%')
            ->orWhere('tags', 'like', '%'.$seed.'%');
    }
    public function scopeRefine($query, $filters)
    {
        foreach ($filters as $key => $value) {
            switch ($key) {
                case 'category':
                    $children = \Cache::remember('progeny_of_'.$value, 15, function () use ($value) {
                        Category::progeny($value, $children, ['id']);
                        return $children;
                    });
                    $children[] = ['id' => $value * 1];
                    $query->whereIn('category_id', $children);
                break;
                // case 'conditions':
                //     $query->where('condition', 'LIKE', $value);
                // break;
                case 'brands':
                   $query->where('brand', 'LIKE', $value);
                break;
                case 'min':
                case 'max':
                    $min = array_key_exists('min', $filters) ? (trim($filters['min']) != '' ? $filters['min'] : '') : '';
                    $max = array_key_exists('max', $filters) ? (trim($filters['max']) != '' ? $filters['max'] : '') : '';
                    if ($min != '' && $max != '') {
                        $query->whereBetween('price', [$min, $max]);
                    } elseif ($min == '' && $max != '') {
                        $query->where('price', '<=', $max);
                    } elseif ($min != '' && $max == '') {
                        $query->where('price', '>=', $min);
                    }
                break;
                default:
                    if ($key != 'category_name' && $key != 'search' && $key != 'page') {
                        //changing url encoded character by the real ones
                        $value = urldecode($value);
                        //applying filter to json field
                        $query->whereRaw("features LIKE '%\"".$key.'":%"%'.str_replace('/', '%', $value)."%\"%'");
                    }
                break;
            }
        }
    }
    public function scopeName($query, $input)
    {
        if (trim($input) != '') {
            $query->where('name', 'LIKE', "%$input%");
        }
    }
    public function scopeType($query, $input)
    {
        if (count($input) > 0) {
            $query->whereIn('category_id', $input);
        }
    }
    public function getStatusLettersAttribute()
    {
        if ($this->status == 0) {
            return trans('globals.inactive');
        }
        return trans('globals.active');
    }
    public function scopeFree($query)
    {
        if (!config('app.offering_free_products')) {
            $query->where('type', '<>', 'freeproduct');
        }
    }
    /**
     * Products tags filter.
     *
     * @param [object] $query, which is the laravel builder
     * @param [string] $attr,  which is used to evaluate the where In (categories requiered)
     * @param [array]  $data,  which is the info to be evaluated
     */
    public function scopeLike($query, $attr = [], $search = [])
    {
        //if the search contains a string of words, we split them in an array
        if (!is_array($search)) {
            $search = explode(' ', preg_replace('/\s+/', ' ', trim($search)));
        }
        $needle = '(';
        if (!is_array($attr)) {
            $attr = [$attr];
        }
        foreach ($attr as $key) {
            foreach ($search as $word) {
                if (trim($word) != '') {
                    $needle .= $key." like '%".$word."%' or ";
                }
            }
        }
        $needle = rtrim($needle, ' or ').')';
        $query->whereRaw($needle);
        return $query;
    }
    /**
     * categories filter.
     *
     * @param [object] $query, which is the laravel builder
     * @param [string] $attr,  which is used to evaluate the where In (categories requiered)
     * @param [array]  $data,  which is the info to be evaluated
     */
    public function scopeInCategories($query, $attr, $data = [])
    {
        if (count($data) > 0 && empty($data['category'])) {
            $query->whereIn($attr, $data);
        } elseif (isset($data['category'])) {
            $query->where($attr, '=', $data['category']);
        }
        return $query;
    }
    public function getNumOfReviewsAttribute()
    {
        return $this->rate_count.' '.\Lang::choice('store.review', $this->rate_count);
    }
}

resources/views/partial/breadcrumbs.blade.php
<div class="navbar-wrapper container">
	{!! Breadcrumbs::render('productDetail', $product) !!}
</div>

resources/views/partial/footer.blade.php
<div class="col-md-12 f-footer-area">

    <div class="row footer-row">
        <div class="col-xs-4 col-sm-4 col-md-4">
            <img class="logo-jpg" src="img/pt-default/logo.png">
            
        </div>

        <div class="col-xs-4 col-sm-4 col-md-4 menu">
            <h3 class="widget-title heading-title">Contact Us</h3>
            <div class="line line-30"></div>

        </div>

        <div class="col-xs-4 col-sm-4 col-md-4 newsletter">
            
            <div class="footer-right">
                <h3 class="widget-title heading-title">
                        Сошиал                  </h3>
                <div class="line line-30"></div>
                <ul>
                    <li>
                        <div class="social-icons">
                            <ul>
                                <li class="icon-facebook fa-lg"><a href="https://www.facebook.com/" target="_blank" title="Become our fan"><i class="fa fa-facebook"></i></a>
                                </li>

                                <li class="icon-twitter fa-lg"><a href="http://twitter.com/#" target="_blank" title="Follow us"><i class="fa fa-twitter"></i></a>
                                </li>

                                <li class="icon-google fa-lg"><a href="https://plus.google.com/u/0/#" target="_blank" title="Get updates"><i class="fa fa-google-plus"></i></a>
                                </li>

                                <li class="icon-instagram fa-lg"><a href="https://www.instagram.com/" target="_blank" title="Follow us"><i class="fa fa-instagram"></i></a>
                                </li>                            
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

    </div>

    <div class="fourth-footer-area row ">

        <div id="copy-right" class="copy-right col-sm-12">
            <div class="col-sm-8">
                Copyright ©. 2017 All Right Reserved. Techstar Agency.
            </div>

        </div>
        <!-- end #copyright -->

    </div>

</div>
@section('scripts') @parent

@stop

resources/views/partial/message.blade.php
<?php

/**
 * Contains the notify plugin style
 *
 * @var string
 */
$class = Session::get('messageClass') ? Session::get('messageClass') : 'alert alert-success';
$class = is_array($class) ? implode('', $class) : $class;

/**
 * Contains the notify plugin message.
 *
 * @var string / array
 */
$m = Session::get('message');
$m = $m ? (is_array($m) ? Html::ul($m) : '<p>'.$m.'</p>') : '';
$m = $m ? (is_array($m) ? Html::ul($m) : '<p>'.$m.'</p>') : '';

/**
 * Laravel errors message controller
 *
 * @var array
 */
$e = $errors->any() ? Html::ul($errors->all()) : '';

//forgetting flash data to control app notify messages.
Session::forget('message');
Session::forget('messageClass');
Session::save();

?>
@if($m!='' || $e!='')
    <div ng-controller="MessageController"></div>
    @section('scripts')
    @parent
        <script>
            (function(app){
                app.controller('MessageController',['notify',function(notify) {
                  @if($m!='')
                    notify({duration:5000,messageTemplate:'{!! $m !!}',classes:'{{$class}}'});
                  @endif
                  @if($e!='')
                    notify({duration:5000,messageTemplate:'{!! $e !!}',classes:'alert alert-danger'});
                  @endif
                }]);
            })(angular.module("Bella"));
        </script>
    @stop
@endif

resources/views/partial/navigation.blade.php
<div class="navbar-header header-top">
	<div class="header-top-left col-sm-8 col-xs-0">
		<ul>
			<li id="ew_social-4" class="widget-container widget_social">						
				<div class="social-icons">
					<ul>
						<li class="icon-facebook"><a href="https://www.facebook.com/pg/Make-up-artist-Bella-451092605001683/videos/?ref=page_internal" target="_blank" title="Become our fan"><i class="fa fa-facebook"></i></a></li>				
						
						<li class="icon-twitter"><a href="http://twitter.com/#" target="_blank" title="Follow us"><i class="fa fa-twitter"></i></a></li>
						
						<li class="icon-google"><a href="https://plus.google.com/u/0/#" target="_blank" title="Get updates"><i class="fa fa-google-plus"></i></a></li>
					
						<li class="icon-instagram"><a href="https://www.instagram.com/isabellabellasmakeup/" target="_blank" title="Follow us"><i class="fa fa-instagram"></i></a></li>
						
				</div>
			</li>
		</ul>
	</div>
	<div class="header-top-right col-sm-4 col-xs-12">
		<ul>
			@include('user.partial.menu_top')
				
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style="">
					<span>{{ trans('store.productsInWishList') }}(0)</span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="{{ route('orders.show_wish_list') }}">{{ trans('store.wish_list') }}</a></li>
					<li><a href="{{ route('orders.show_list_directory') }}">{{ trans('store.your_wish_lists') }}</a></li>
				</ul>
			</li>

			@if(Auth::user())
				<li class="dropdown " id="push-notices" ng-controller="PushNoticesController"  ng-click="check()" ng-focus="check()">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
						<span class="badge badge-notifications ng-hide" ng-cloak  ng-show="push">[[push]]</span>
						<span class="fui fui-chat"></span>{{ trans('globals.notices') }}
						<span class="visible-xs-inline">
							<span class="caret"></span>
						</span>
					</a>
					<ul class="dropdown-menu notices" role="menu" ng-if="notices.length">
						<li ng-repeat="notice in notices" class="[[notice.status]]">
							<a href="[[getLink(notice)]]" ng-click="check(notice)">[[getDesc(notice)]]</a>
						</li>
						<li>{!! link_to('user/notices/list', trans('globals.all')) !!}</li>
					</ul>
				</li>

				@if (config('app.offering_user_points'))
				<li>
					<a href="{{ route('paypal.buy_points') }}" ng-controller = "PushUsersPoints" ng-init = "pusher()">
						<span class="badge badge-points ng-hide" ng-cloak ng-show = "points" >[[ points | thousandSuffix ]]</span>
						<span class="fui fui-radio-unchecked"></span>{{ trans('store.price') }}
					</a>
				</li>
				@endif
			@endif

			@if (config('app.offering_free_products'))
				<li>
					<a href="{{ route('freeproducts.search') }}">
						<span class="fui fui-star-2"></span>{{ trans('globals.products') }}
						<span class="badge badge-freeproducts">{{ trans('globals.free') }}</span>
					</a>
				</li>
			@endif
		</ul>
	</div>
</div>
<div class="header-search-row">
	<a class="logo col-md-3" href="/home">
		@if($main_company['logo'])
			<span class="navbar-brand-text">
				<img class="logo-img" src="{{$main_company['logo']}}" alt="">
			</span>
		@else
			<span class="navbar-brand-text">
				<img src="img/logo-1.png" >
			</span>
		@endif

	</a>
	<nav ng-controller="CategoriesController" class="cat-controller-nav col-md-9">
	{!! Form::model(Request::all(),['url'=> action('ProductsController@index'), 'method'=>'GET', 'id'=>'searchForm']) !!}
	<div class="search-nav">

		<span class="categories-search">
			<button  type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
				<span ng-bind="catSelected.name || '{{ isset($categories_menu[Request::get('category')]['name']) ? $categories_menu[Request::get('category')]['name'] : trans('store.all_categories') }}'">
					{{ isset($categories_menu[Request::get('category')]['name']) ? $categories_menu[Request::get('category')]['name'] : trans('store.all_categories') }}
					</span> <span class="caret">
				</span>
			</button>
			<ul class="dropdown-menu" role="menu">
				@foreach($categories_menu as $categorie_menu)
					<li >
						<a href="javascript:void(0)"
						   ng-click="setCategorie({{ $categorie_menu['id'] }},'{{ $categorie_menu['name'] }}')" >
							{{ $categorie_menu['name'] }}
						</a>
					</li>
				@endforeach

			</ul>
		</span>
		<input type="hidden" name="category" value="[[refine() || '{{Request::get('category')}}']]"/>

		@include('partial.search_box',['angularController' => 'AutoCompleteCtrl', 'idSearch'=>'search'])

		<span class="search-btn">
			<button class="btn btn-default glyphicon glyphicon-search" type="submit"></button>
		</span>



		<div class="cart">

		<ul class="nav navbar-nav">
			<li class="dropdown">
				<a href="#cart" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					@if(Auth::user()&&Auth::user()->getCartCount())
					<span class="badge badge-cart">{{ Auth::user()->getCartCount() }} </span>
					@elseif(!Auth::user() && is_array(Session::get('user.cart_content')) && array_sum(Session::get('user.cart_content')))
					<span class="badge badge-cart">{{ array_sum(Session::get('user.cart_content')) }} </span>
					@endif

					<span class="glyphicon glyphicon-shopping-cart" style="font-size: 10px; color: white;"> 0ITEM ₮0.00</span>

				</a>

	            @if(Auth::user() && Auth::user()->getCartCount() > 0)
	                <ul class="dropdown-menu" role="menu">
	                    @foreach(Auth::user()->getCartContent() as $orderDetail)
	                        <li>
	                            <a href="{{ route('products.show',[$orderDetail->product->id]) }}" >

	                                    <img src="{{ $orderDetail->product->FirstImage }}" alt="{{ $orderDetail->product->name }}" width="32" height="32"/>
	                                    {{ $orderDetail->product->name }}
	                                     - {{ trans('store.quantity') }}: {{ $orderDetail->quantity }}

	                            </a>
	                        </li>
	                    @endforeach
	                    <li><a class="btn btn-default" href="{{ route('orders.show_cart') }}" role="button">{{ trans('store.view_cart') }}</a></li>
	                </ul>
	            @elseif(!Auth::user() && is_array(Session::get('user.cart_content')))
	                <ul class="dropdown-menu cart" role="menu">
	                @foreach(Session::get('user.cart_content') as $product_id => $quantity)
	                @if($product=\App\Product::find($product_id))
	                    <li>
	                        <a href="{{ route('products.show',[$product_id]) }}" >

	                                <img src="{{ $product->first_image }}" width="32" height="32"/>
	                                {{ $product->name }}
	                                 - {{ trans('store.quantity') }}: {{ $quantity }}

	                        </a>
	                    </li>
	                @endif
	                @endforeach
	                <li><a class="btn btn-default" href="{{ route('orders.show_cart') }}" role="button" >{{ trans('store.view_cart') }}</a></li>
	                </ul>
	            @endif
			</li>
		</ul>
	</div>

</div>
{!! Form::close() !!}
</nav>
</div>

@include('partial.navigation_bottom')

resources/views/partial/navigation_basic.blade.php
<div class="navbar-wrapper">
    <nav class="navbar">
        <div class="container">
            <div class="navbar-header">
                <div class="navbar-brand">
                    <a href="/home" class="navbar-brand">
                        {{ $main_company['name'] }}
                        <br>
                        
                    </a>
                </div>
            </div>
            @include('partial.navigation_help')
        </div>
    </nav>
</div>

resources/views/partial/navigation_bottom.blade.php
<div class="header-bottom-content">
    <div class="col-md-3 col-sm-2 col-xs-12">
       <h3 class="full-category" id="full-category">Бүх ангилал<i class="fa fa-navicon"></i></h3> 
    </div>
    <div class="col-md-9 col-sm-10 col-xs-12">
        <ul class="line-menu">
            <li><a class="kk-1" href="{{ route('home') }}">Нүүр</a></li>
            <li><a class="kk-1" href="{{ route('products') }}">Бүтээгдэхүүний жагсаалт</a></li>
        </ul>
    </div>
</div>

resources/views/partial/navigation_help.blade.php
<ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <span class="fui fui-question-circle"></span>
            <!-- {{ trans('globals.help') }} -->
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
            <?php $menu=\Menu::help(true);?>
            @foreach ($menu as $item)
            <li class="{{isset($item['class'])?$item['class']:''}} {{ Utility::active($item['route']) }}" >
                <a href='{{$item['route']}}'>@if(isset($item['icon']))<span class="{{$item['icon']}}"></span>@endif {{$item['text']}} @if(isset($item['cont'])&&$item['cont']>0)<span class="badge pull-right">{{$item['cont']}}</span>@endif </a>
            </li>
            @if(isset($item['divider']))<li class="divider"></li>@endif
            @endforeach
        </ul>
    </li>
</ul>

resources/views/partial/search_box.blade.php
<div ng-controller="{{ $angularController }}" class="search-input">

		<angucomplete-alt
		id="{{ $idSearch }}"
          input-name="{{ $idSearch }}"
          initial-value="{{ isset($search) && $search ? $search : '' }}"
          placeholder="{{ trans('globals.search').'...' }}"
          pause="100"
          selected-object="selectedItem"
          match-class="highlight"
          remote-url="/search/?group={{ isset($group) ? $group : 0 }}&suggest={{ !isset($suggest) ? 1 : 0 }}&crit="
          auto-match="true"
          image-field="image"
          remote-url-data-field="products"
          search-fields="name"
          title-field="name"
          description-field="description"
          text-searching="{{ trans('globals.searching') }}"
          text-no-results="{{ trans('globals.no_results') }}"
          minlength="3"
          input-class="form-control"/>
          
</div>

resources/views/partial/social_tags.blade.php
<meta name="description" content = "{{ $description }}">

<meta name = "twitter:card" content = "summary_large_image">
<meta name = "twitter:site" content = "@{{ $main_company['twitter'] }}">
<meta name = "twitter:title" content = "{{ $title }}">
<meta name = "twitter:image" content = "{{ $image }}">
<meta name = "twitter:description" content = "{{ $description }}">

<meta property = "og:title" content = "{{ $title }}" />
<meta property = "og:site_name" content = "{{ $main_company['website_name']}}"/>
<meta property = "og:description" content = "{{ $description }}" />
<meta property = "og:image" content = "{{ $image }}" >
<meta property = "og:type" content = "og:product" />
<meta property = "og:url" content = "{{ Request::url() }}" />
<meta property = "fb:app_id" content  =  "{{ env('FB_APP_ID')  }}" />
<meta property = "og:image:width" content = "450"/>
<meta property = "og:image:height" content = "298"/>


<script type="application/ld+json">
    {
      "@context": "http://schema.org/",
      "@type": "Product",
      "name": "{{$title}}",
      "image": "{{$image}}",
      "description": "{{$description}}",
      "mpn": "{{$id}}",
      "brand": {
        "@type": "Thing",
        "name": "{{$brand}}"
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "{{$rate_val}}",
        "reviewCount": "{{$rate_count}}"
      }
    }
</script>